/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent() {
  return (
    <div className="flex flex-col items-center pb-20">
      <div className="self-stretch w-full bg-white bg-opacity-10 min-h-[8px] max-md:max-w-full" />
      <img
        loading="lazy"
        srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/654a2428e98c9f4bdfdd1616b6596ffdc142b9d6bd9a3424613fa6a66c1a41c1?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/654a2428e98c9f4bdfdd1616b6596ffdc142b9d6bd9a3424613fa6a66c1a41c1?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/654a2428e98c9f4bdfdd1616b6596ffdc142b9d6bd9a3424613fa6a66c1a41c1?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/654a2428e98c9f4bdfdd1616b6596ffdc142b9d6bd9a3424613fa6a66c1a41c1?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/654a2428e98c9f4bdfdd1616b6596ffdc142b9d6bd9a3424613fa6a66c1a41c1?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/654a2428e98c9f4bdfdd1616b6596ffdc142b9d6bd9a3424613fa6a66c1a41c1?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/654a2428e98c9f4bdfdd1616b6596ffdc142b9d6bd9a3424613fa6a66c1a41c1?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/654a2428e98c9f4bdfdd1616b6596ffdc142b9d6bd9a3424613fa6a66c1a41c1?apiKey=4dc5fe3e64f2435f8521095d1d95b761&"
        className="mt-96 aspect-square w-[50px] max-md:mt-10"
      />
      <div className="mt-4 text-4xl leading-9 text-center text-orange-100">
        BULU{" "}
      </div>
      <div className="mt-8 text-2xl font-bold leading-9 text-center text-orange-100">
        Aplikasi pertama bagi para pecinta bulu tangkis
      </div>
      <div className="mt-5 text-lg leading-6 text-center text-orange-100">
        Tingkatkan kemampuan bermain bulu tangkismu, bagikan momen terbaik
        bermain dengan teman-teman, kirim video permainanmu untuk direview oleh
        pelatih berpengalaman
      </div>
      <div className="justify-center items-center px-16 py-5 mt-3.5 max-w-full text-base font-bold tracking-wider leading-5 text-center text-orange-100 whitespace-nowrap bg-teal-500 rounded-3xl w-[360px] max-md:px-5">
        MULAI
      </div>
      <div className="flex gap-5 justify-between mt-8">
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/cc49f8cc36994eca8942bd65b5d6ac913da889bd7275e4a283ef1985d988b0ed?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc49f8cc36994eca8942bd65b5d6ac913da889bd7275e4a283ef1985d988b0ed?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc49f8cc36994eca8942bd65b5d6ac913da889bd7275e4a283ef1985d988b0ed?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc49f8cc36994eca8942bd65b5d6ac913da889bd7275e4a283ef1985d988b0ed?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc49f8cc36994eca8942bd65b5d6ac913da889bd7275e4a283ef1985d988b0ed?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc49f8cc36994eca8942bd65b5d6ac913da889bd7275e4a283ef1985d988b0ed?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc49f8cc36994eca8942bd65b5d6ac913da889bd7275e4a283ef1985d988b0ed?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/cc49f8cc36994eca8942bd65b5d6ac913da889bd7275e4a283ef1985d988b0ed?apiKey=4dc5fe3e64f2435f8521095d1d95b761&"
          className="shrink-0 aspect-square w-[50px]"
        />
        <img
          loading="lazy"
          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/e16720bdb5ab7e7ba89096a81b7b9fc59f5766b1e19820fabb5d9d9d023aff4f?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/e16720bdb5ab7e7ba89096a81b7b9fc59f5766b1e19820fabb5d9d9d023aff4f?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e16720bdb5ab7e7ba89096a81b7b9fc59f5766b1e19820fabb5d9d9d023aff4f?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/e16720bdb5ab7e7ba89096a81b7b9fc59f5766b1e19820fabb5d9d9d023aff4f?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/e16720bdb5ab7e7ba89096a81b7b9fc59f5766b1e19820fabb5d9d9d023aff4f?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/e16720bdb5ab7e7ba89096a81b7b9fc59f5766b1e19820fabb5d9d9d023aff4f?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/e16720bdb5ab7e7ba89096a81b7b9fc59f5766b1e19820fabb5d9d9d023aff4f?apiKey=4dc5fe3e64f2435f8521095d1d95b761&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/e16720bdb5ab7e7ba89096a81b7b9fc59f5766b1e19820fabb5d9d9d023aff4f?apiKey=4dc5fe3e64f2435f8521095d1d95b761&"
          className="shrink-0 w-10 aspect-[0.8]"
        />
      </div>
    </div>
  );
}